#!/bin/sh

# impp - Interactive Markdown preprocessor

PROMPT='%>> '
COLOUR=yellow


echo ' _____ ___ ___ '
echo '|     | , | , |'
echo '|_|_|_|  _|  _|'
echo '      |_| |_|  '
echo
echo "Welcome to MPP 0.1 on $(uname -mo)"
echo 'Copyright (c) Joan Josep Ordinas Rosa (2020) <joan.ordinas@pm.me>'
echo

exec rlwrap --prompt-colour="$COLOUR"       \
            --substitute-prompt="$PROMPT"   \
            "${0%impp}mpp" "$@"

# vim:ts=4:sw=4:ai:et:fileencoding=utf-8:syntax=sh
