#!/bin/sh

# impp -- Interactive MPP

# CLS
case $TERM in
	linux|xterm*|screen*)
		echo -n -e '\033[0m\033[1;1H\033[2J'
        ;;
	*)
		type clear >/dev/null 2>&1 && clear
        ;;
esac

# Logo
echo ' _____ ___ ___ '
echo '|     | , | , |'
echo '|_|_|_|  _|  _|'
echo '      |_| |_|  '
echo

# Simple interface, more like TRAC
exec rlwrap --pass-sigint-as-sigterm "${0%impp}mpp" -D__IMPP__ "$@"

# With prompt
PROMPT='#>> '
COLOUR=yellow

exec rlwrap --pass-sigint-as-sigterm        \
            --prompt-colour="$COLOUR"       \
            --substitute-prompt="$PROMPT"   \
            "${0%impp}mpp"                  \
            -D__IMPP__                      \
            "$@"

# vim:ts=4:sw=4:ai:et:fileencoding=utf-8:syntax=sh
