#!/bin/sh

# impp - Interactive Markdown preprocessor

case $TERM in
	linux|xterm*|screen*)
		echo -en '\e[0m\e[1;1H\e[2J'
	;;
	*)
		clear
	;;
esac

echo ' _____ ___ ___ '
echo '|     | , | , |'
echo '|_|_|_|  _|  _|'
echo '      |_| |_|  '
echo
echo "Welcome to MPP 0.1"
echo

# Simple interface
#exec rlwrap --pass-sigint-as-sigterm "${0%impp}mpp" "$@"

# With prompt
PROMPT='#>> '
COLOUR=yellow

exec rlwrap --pass-sigint-as-sigterm        \
            --prompt-colour="$COLOUR"       \
            --substitute-prompt="$PROMPT"   \
            "${0%impp}mpp" "$@"

# vim:ts=4:sw=4:ai:et:fileencoding=utf-8:syntax=sh
