#!/bin/sh

# mpp - Markdown preprocessor

readonly DATADIR="/usr/local/share/MPP"
readonly PRELUDE="$DATADIR/prelude.mpp"
readonly ENVIRON="-DUID=$UID -DHOME=$HOME -DPWD='$PWD' -DLANG=$LANG -DPID=$$"

# Must be "exec" to recycle the PID!
exec gpp \
    -U '${\W' '\W}' '\B' '\B' '\W}' '{' '}' '$' '' \
    +sccc '#|' '|#' ''          \
    +sccc '&\n' '' ''           \
    --warninglevel 2            \
    --nostdinc -I "$DATADIR"    \
    --include "$PRELUDE"        \
    $ENVIRON -DNL="\n"          \
    -x -m "$@"

# vim:ts=4:sw=4:ai:et:fileencoding=utf-8:syntax=sh
