#!/bin/sh

# mpp - Markdown preprocessor

readonly PRELUDE="share/_prelude.mpp"
readonly INCLUDE="./share"
readonly ENVIRON="-DUID=$UID -DHOME=$HOME -DPWD='$PWD' -DLANG=$LANG -DPID=$$"

exec gpp \
    -U '$' '' '{\W' '\B' '\W}' '{' '}' '$' '' \
    +siis '<!--' '-->' ''       \
    +siis '`'  '`' ''           \
    +siis '\n```' '\n```' ''    \
    +siis '\n~~~' '\n~~~' ''    \
    +sccc '#|' '|#' ''          \
    +sccc '#;' '\n' ''          \
    +sccc '&\n' '' ''           \
    +siqi "'" "'" ''            \
    +siQi '"' '"' ''            \
    +sccc '#c<' '>' ''          \
    +sCCC '#C<' '>' ''          \
    +ssss '#s<' '>' ''          \
    +sSSS '#S<' '>' ''          \
    +sqqq '#q<' '>' ''          \
    +sQQQ '#Q<' '>' ''          \
    --warninglevel 2            \
    --nostdinc -I "$INCLUDE"    \
    --include "$PRELUDE"        \
    $ENVIRON -DNL="\n"          \
    -x -m "$@"

# vim:ts=4:sw=4:ai:et:fileencoding=utf-8:syntax=sh
